const MachineList = [
  {
    address: "北京-GTX1080Ti",
    ip: "cvp.g2link.cn",
    port: "20044",
    account: "g2link",
    type: "在线算法服务器",
    note: "公网地址：124.204.79.221;映射端口：27010-27020;本地端口跟互联网端口相同",
  },
  {
    address: "壹米滴答无锡园区",
    ip: "cvp.g2link.cn",
    port: "20046",
    account: "g2",
    type: "算法服务器",
    note: "2020.9.8机房搬迁，更新",
  },
  {
    address: "普洛斯上海奉贤（奉城）园区",
    ip: "cvp.g2link.cn",
    port: "20021",
    account: "g2",
    type: "算法服务器",
    note: "两个IP都可以远程登陆，两个账号都有效",
  },
  {
    address: "普洛斯沈阳邦送园区",
    ip: "cvp.g2link.cn",
    port: "20026",
    account: "g2",
    type: "算法服务器",
    note: "",
  },
  {
    address: "广佛云埔",
    ip: "cvp.g2link.cn",
    port: "20060",
    account: "g2",
    type: "算法服务器",
    note: "通道占用和人员离岗",
  },
  {
    address: "壹米滴答上海园区",
    ip: "cvp.g2link.cn",
    port: "20007",
    account: "g2",
    type: "算法服务器",
    note: "向日葵352599325/g2link",
  },
  {
    address: "美团",
    ip: "cvp.g2link.cn",
    port: "20062",
    account: "meituan_cv",
    type: "算法服务器",
    note: "月台车位占用检测和车牌识别",
  },
  {
    address: "上海青浦香花桥工地",
    ip: "cvp.g2link.cn",
    port: "20049",
    account: "g2link/yons",
    type: "算法服务器",
    note: "智慧工地",
  },
  {
    address: "武汉杰之行",
    ip: "cvp.g2link.cn",
    port: "20051",
    account: "jzx",
    type: "算法服务器",
    note: "金融监管: 192.168.21.245 对外;192.168.2.101局域网",
  },
  {
    address: "郑州好想你工地",
    ip: "cvp.g2link.cn",
    port: "20054",
    account: "g2",
    type: "算法服务器",
    note: "智慧工地",
  },
  {
    address: "环普祝桥",
    ip: "cvp.g2link.cn",
    port: "20058",
    account: "luoqi",
    type: "算法服务器",
    note: "通道占用和人员离岗",
  },
  {
    address: "上海南汇",
    ip: "cvp.g2link.cn",
    port: "20076",
    account: "g2link",
    type: "算法服务器",
    note: "月台检测",
  },
  {
    address: "武汉中百",
    ip: "cvp.g2link.cn",
    port: "20074",
    account: "g2link",
    type: "算法服务器",
    note: "月台检测",
  },
  {
    address: "东莞谢岗",
    ip: "cvp.g2link.cn",
    port: "20078",
    account: "yons/g2link",
    type: "算法服务器",
    note: "智慧工地",
  },
  {
    address: "台山",
    ip: "cvp.g2link.cn",
    port: "20082",
    account: "yons",
    type: "算法服务器",
    note: "",
  },
  {
    address: "海南澄迈",
    ip: "cvp.g2link.cn",
    port: "20084",
    account: "g2link",
    type: "算法服务器",
    note: "智慧工地",
  },
  {
    address: "天津邦均",
    ip: "cvp.g2link.cn",
    port: "20086",
    account: "g2link",
    type: "算法服务器",
    note: "",
  },
];

export default MachineList;
